Resources:
  AppSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: For ssh on port 22 access and 8080 port access for Customer App
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "8080"
          ToPort: "8080"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "9090"
          ToPort: "9090"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "3000"
          ToPort: "3000"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "9100"
          ToPort: "9100"
          CidrIp: 0.0.0.0/0          
  AppAndMonitor:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0d5eff06f840b45e9 # ImageId depends on a region. The current image is valid ONLY in US-EAST-1
      KeyName: lt-key
      IamInstanceProfile: s3-admin
      SecurityGroups:
        - !Ref AppSG
      UserData: !Base64 |
        #!/bin/sh
        export PATH=/usr/local/bin:$PATH;

        yum update
        yum install docker -y
        service docker start
        # Docker login notes:
        #   - For no email, just put one blank space.
        #   - Also the private repo protocol and version are needed for docker
        #     to properly setup the .dockercfg file to work with compose
        #  # docker log in 
        #  docker login --username="h1m1w1" --password=env.password --email="h1m1w1@googlemail.com" https://index.docker.io/v1/
        mv /root/.dockercfg /home/ec2-user/.dockercfg
        chown ec2-user:ec2-user /home/ec2-user/.dockercfg
        usermod -a -G docker ec2-user
        curl -L https://github.com/docker/compose/releases/download/v2.10.0/docker-compose-linux-x86_64 > /usr/local/bin/docker-compose
        
        chmod +x /usr/local/bin/docker-compose
        chown root:docker /usr/local/bin/docker-compose
        mkdir /etc/prometheus/
        
        # use stefanprodan tamplate to build prometheus and grafana to monitor docker container
        git clone https://github.com/stefanprodan/dockprom            
        sudo ADMIN_USER=admin ADMIN_PASSWORD=admin /usr/local/bin/docker-compose -f /dockprom/docker-compose.yml up -d

        # Run docker-compose
        # chown ec2-user:ec2-user /home/ec2-user/docker-compose.yml
        /usr/local/bin/docker-compose up -d
